---
# defaults file for deploy_netdata
IPADDR: "{{ ansible_default_ipv4.address }}"
pkgs:
       - zlib1g-dev
       - uuid-dev
       - libmnl-dev
       - gcc
       - make
       - git
       - autoconf
       - autoconf-archive
       - autogen
       - automake
       - pkg-config
       - curl
