---
# tasks file for deploy_netdata
  - name: update packages
    apt:
     update_cache: yes
     upgrade: 'yes'

  - name: preparing installing netdata
    yum: name={{ pkgs }} state=latest

  - name: install netdata
    yum: name=netdata state=latest

  - name: start netdata
    service: name=netdata state=started enabled=yes

  - name: replace 127****** to int IP
    lineinfile:
       dest: /etc/netdata/netdata.conf
       regexp: 'bind socket to IP = 127.0.0.1'
       line: '        bind socket to IP = {{ IPADDR }}'
       backrefs: yes

  - name: restart netdata
    service: name=netdata state=restarted

